name: Publish Plugins

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@daytonaio'

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            daytona:
              - 'plugins/daytona/**'
            auth-backend-module-daytona-provider:
              - 'plugins/auth-backend-module-daytona-provider/**'

      - if: steps.changes.outputs.daytona == 'true' || steps.changes.outputs.auth-backend-module-daytona-provider == 'true'
        name: Install dependencies
        run: |
          yarn
          yarn tsc
          yarn build:all

      - if: steps.changes.outputs.daytona == 'true' || github.event_name == 'workflow_dispatch'
        name: Publish @daytonaio/backstage-plugin-daytona
        run: |
          cd plugins/daytona
          yarn publish --non-interactive --access public
        continue-on-error: true

      - if: steps.changes.outputs.auth-backend-module-daytona-provider == 'true' || github.event_name == 'workflow_dispatch'
        name: Publish @daytonaio/backstage-plugin-auth-backend-module-daytona-provider
        run: |
          cd plugins/auth-backend-module-daytona-provider
          yarn publish --non-interactive --access public
        continue-on-error: true
